files = {
"../../snd/F1S1.aif" : ['struck', 'laChouffe', 'belgium', 'tulip', 'forward', ' all'],
"../../snd/F1S2.aif" : ['struck', 'piraat', 'belgium', 'tulip', 'forward', 'all'],
"../../snd/F1S3.aif" : ['struck', 'corsendonk', 'belgium', 'tulip', 'forward', 'all'],
"../../snd/F1S4.aif" : ['struck', 'tripelKarmeliet', 'belgium', 'tulip', 'forward', 'all'],
"../../snd/F1S5.aif" : ['struck', 'goudenCarolus', 'belgium', 'chalice', 'forward', 'all'],
"../../snd/F1S6.aif" : ['struck', 'kwak', 'belgium', 'testTube', 'forward', 'all'],
"../../snd/F1S7.aif" : ['struck', 'laFinDuMonde', 'canada', 'tulip', 'forward', 'all'],
"../../snd/F1S8.aif" : ['struck', 'duvel', 'belgium', 'tulip', 'forward', 'all'],
"../../snd/F1S9.aif" : ['struck', 'maudite', 'canada', 'snifter', 'forward', 'all'],
"../../snd/F1S10.aif" : ['struck', 'deliriumTremens', 'belgium', 'snifter', 'forward', 'all'],
"../../snd/F1S11.aif" : ['kill'], # do not use
"../../snd/F1S12.aif" : ['struck', 'plainSnifter', 'noCOA', 'snifter', 'forward', 'all'],
"../../snd/F1S13.aif" : ['struck', 'bellsSnifter', 'usa', 'snifter', 'forward', 'all'],
"../../snd/F1S14.aif" : ['struck', 'fishbowlSnifter', 'noCOA', 'snifter', 'forward', 'all'],
"../../snd/F1S15.aif" : ['kill'], # do not use
"../../snd/F1S16.aif" : ['struck', 'hommelbier', 'belgium', 'snifter', 'forward', 'all'],
"../../snd/F1S17.aif" : ['struck', 'decantingChalice', 'noCOA', 'chalice', 'forward', 'all'],
"../../snd/F1S18.aif" : ['struck', 'augustjin', 'belgium', 'chalice', 'forward', 'all'],
"../../snd/F1S19.aif" : ['struck', 'leffe', 'belgium', 'chalice', 'forward', 'all'],
"../../snd/F1S20.aif" : ['struck', 'troisPistoles', 'canada', 'chalice', 'forward', 'all'],
"../../snd/F1S21.aif" : ['struck', 'chimay', 'belgium', 'chalice', 'forward', 'all'],
"../../snd/F1S22.aif" : ['kill'], # do not use
"../../snd/F1S23.aif" : ['struck', 'trappistesRochefort', 'belgium', 'chalice', 'forward', 'all'],
"../../snd/F1S24.aif" : ['struck', 'grottenbier', 'belgium', 'chalice', 'forward', 'all'],
"../../snd/F1S25.aif" : ['struck', 'kasteel', 'belgium', 'chalice', 'forward', 'all'],
"../../snd/F1S26.aif" : ['struck', 'konigshoeven', 'belgium', 'chalice', 'forward', 'all'],
"../../snd/F1S27.aif" : ['struck', 'westmalle', 'belgium', 'chalice', 'forward', 'all'],
"../../snd/F1S28.aif" : ['struck', 'stBernardus', 'belgium', 'chalice', 'forward', 'all'],
"../../snd/F1S29.aif" : ['struck', 'tulipPintGlass', 'noCOA', 'pintGlass', 'forward', 'all'],
"../../snd/F1S30.aif" : ['struck', 'samAdamsPint', 'usa', 'pintGlass', 'forward', 'all'],
"../../snd/F1S31.aif" : ['struck', 'ommegangFlute', 'usa', 'flute', 'forward', 'all'],
"../../snd/F1S32.aif" : ['struck', 'rootBeerFloat', 'noCOA', 'tulip', 'forward', 'all'],
"../../snd/F1S33.aif" : ['struck', 'schaflyKolsch', 'usa', 'kolsch', 'forward', 'all'],
"../../snd/F1S34.aif" : ['struck', 'lindemannsFlute', 'belgium', 'flute', 'forward', 'all'],
"../../snd/F1S35.aif" : ['struck', 'ayingerCelebrator', 'germany', 'pokal', 'forward', 'all'],
"../../snd/F1S36.aif" : ['struck', 'footedAleGlass', 'noCOA', 'pokal', 'forward', 'all'],
"../../snd/F1S37.aif" : ['struck', 'gaffelKolsch', 'germany', 'kolsch', 'forward', 'all'],
"../../snd/F1S38.aif" : ['struck', 'plainWeizen', 'noCOA', 'weizen', 'forward', 'all'],
"../../snd/F1S39.aif" : ['struck', 'erdinger', 'germany', 'weizen', 'forward', 'all'],
"../../snd/F1S40.aif" : ['struck', 'paulaner', 'germany', 'weizen', 'forward', 'all'],
"../../snd/F1S41.aif" : ['struck', 'franziskaner', 'germany', 'weizen', 'forward', 'all'],
"../../snd/F1S42.aif" : ['struck', 'weihenstephanerWorldCup', 'germany', 'weizen', 'forward', 'all'],
"../../snd/F1S43.aif" : ['struck', 'schneiderWeisse', 'germany', 'weizen', 'forward', 'all'],
"../../snd/F1S44.aif" : ['struck', 'jever', 'germany', 'pilsner', 'forward', 'all'],
"../../snd/F1S45.aif" : ['struck', 'plainPilsner', 'noCOA', 'pilsner', 'forward', 'all'],
"../../snd/F1S46.aif" : ['struck', 'petrus', 'belgium', 'pokal', 'forward', 'all'],
"../../snd/F1S47.aif" : ['struck', 'kostritzer', 'germany', 'pokal', 'forward', 'all'],
"../../snd/F1S48.aif" : ['struck', 'spatenWillibecker', 'germany', 'becker', 'forward', 'all'],
"../../snd/F1S49.aif" : ['struck', 'hoegaarden', 'belgium', 'pintGlass', 'forward', 'all'],
"../../snd/F1S50.aif" : ['struck', 'samAdamsImperialPint', 'usa', 'pintGlass', 'forward', 'all'],
"../../snd/F1S51.aif" : ['kill'], # do not use
"../../snd/F1S52.aif" : ['struck', 'imperialNonik', 'noCOA', 'pintGlass', 'forward', 'all'],
"../../snd/F1S53.aif" : ['struck', 'glbcPint', 'usa', 'pintGlass', 'forward', 'all'],
"../../snd/F1S54.aif" : ['struck', 'bbcNonik', 'usa', 'pintGlass', 'forward', 'all'],
"../../snd/F1S55.aif" : ['struck', 'samSmithSmall', 'england', 'pintGlass', 'forward', 'all'],
"../../snd/F1S56.aif" : ['struck', 'geordieSchooner', 'england', 'pintGlass', 'forward', 'all'],
"../../snd/F1S57.aif" : ['struck', 'killiansRed', 'england', 'pintGlass', 'forward', 'all'],
"../../snd/F1S58.aif" : ['struck', 'samSmithtulip', 'england', 'pintGlass', 'forward', 'all'],
####'reverse'####
"../../snd/R1S1.aif" : ['struck', 'laChouffe', 'belgium', 'tulip', 'reverse', 'all'],
"../../snd/R1S2.aif" : ['struck', 'piraat', 'belgium', 'tulip', 'reverse', 'all'],
"../../snd/R1S3.aif" : ['struck', 'corsendonk', 'belgium', 'tulip', 'reverse', 'all'],
"../../snd/R1S4.aif" : ['struck', 'tripelKarmeliet', 'belgium', 'tulip', 'reverse', 'all'],
"../../snd/R1S5.aif" : ['struck', 'goudenCarolus', 'belgium', 'chalice', 'reverse', 'all'],
"../../snd/R1S6.aif" : ['struck', 'kwak', 'belgium', 'testTube', 'reverse', 'all'],
"../../snd/R1S7.aif" : ['struck', 'laFinDuMonde', 'canada', 'tulip', 'reverse', 'all'],
"../../snd/R1S8.aif" : ['struck', 'duvel', 'belgium', 'tulip', 'reverse', 'all'],
"../../snd/R1S9.aif" : ['struck', 'maudite', 'canada', 'snifter', 'reverse', 'all'],
"../../snd/R1S10.aif" : ['struck', 'deliriumTremens', 'belgium', 'snifter', 'reverse', 'all'],
"../../snd/R1S11.aif" : ['kill'], # do not use
"../../snd/R1S12.aif" : ['struck', 'plainSnifter', 'noCOA', 'snifter', 'reverse', 'all'],
"../../snd/R1S13.aif" : ['struck', 'bellsSnifter', 'usa', 'snifter', 'reverse', 'all'],
"../../snd/R1S14.aif" : ['struck', 'fishbowlSnifter', 'noCOA', 'snifter', 'reverse', 'all'],
"../../snd/R1S15.aif" : ['kill'], # do not use
"../../snd/R1S16.aif" : ['struck', 'hommelbier', 'belgium', 'snifter', 'reverse', 'all'],
"../../snd/R1S17.aif" : ['struck', 'decantingChalice', 'noCOA', 'chalice', 'reverse', 'all'],
"../../snd/R1S18.aif" : ['struck', 'augustjin', 'belgium', 'chalice', 'reverse', 'all'],
"../../snd/R1S19.aif" : ['struck', 'leffe', 'belgium', 'chalice', 'reverse', 'all'],
"../../snd/R1S20.aif" : ['struck', 'troisPistoles', 'canada', 'chalice', 'reverse', 'all'],
"../../snd/R1S21.aif" : ['struck', 'chimay', 'belgium', 'chalice', 'reverse', 'all'],
"../../snd/R1S22.aif" : ['kill'], # do not use
"../../snd/R1S23.aif" : ['struck', 'trappistesRochefort', 'belgium', 'chalice', 'reverse', 'all'],
"../../snd/R1S24.aif" : ['struck', 'grottenbier', 'belgium', 'chalice', 'reverse', 'all'],
"../../snd/R1S25.aif" : ['struck', 'kasteel', 'belgium', 'chalice', 'reverse', 'all'],
"../../snd/R1S26.aif" : ['struck', 'konigshoeven', 'belgium', 'chalice', 'reverse', 'all'],
"../../snd/R1S27.aif" : ['struck', 'westmalle', 'belgium', 'chalice', 'reverse', 'all'],
"../../snd/R1S28.aif" : ['struck', 'stBernardus', 'belgium', 'chalice', 'reverse', 'all'],
"../../snd/R1S29.aif" : ['struck', 'tulipPintGlass', 'noCOA', 'pintGlass', 'reverse', 'all'],
"../../snd/R1S30.aif" : ['struck', 'samAdamsPint', 'usa', 'pintGlass', 'reverse', 'all'],
"../../snd/R1S31.aif" : ['struck', 'ommegangFlute', 'usa', 'flute', 'reverse', 'all'],
"../../snd/R1S32.aif" : ['struck', 'rootBeerFloat', 'noCOA', 'tulip', 'reverse', 'all'],
"../../snd/R1S33.aif" : ['struck', 'schaflyKolsch', 'usa', 'kolsch', 'reverse', 'all'],
"../../snd/R1S34.aif" : ['struck', 'lindemannsFlute', 'belgium', 'flute', 'reverse', 'all'],
"../../snd/R1S35.aif" : ['struck', 'ayingerCelebrator', 'germany', 'pokal', 'reverse', 'all'],
"../../snd/R1S36.aif" : ['struck', 'footedAleGlass', 'noCOA', 'pokal', 'reverse', 'all'],
"../../snd/R1S37.aif" : ['struck', 'gaffelKolsch', 'germany', 'kolsch', 'reverse', 'all'],
"../../snd/R1S38.aif" : ['struck', 'plainWeizen', 'noCOA', 'weizen', 'reverse', 'all'],
"../../snd/R1S39.aif" : ['struck', 'erdinger', 'germany', 'weizen', 'reverse', 'all'],
"../../snd/R1S40.aif" : ['struck', 'paulaner', 'germany', 'weizen', 'reverse', 'all'],
"../../snd/R1S41.aif" : ['struck', 'franziskaner', 'germany', 'weizen', 'reverse', 'all'],
"../../snd/R1S42.aif" : ['struck', 'weihenstephanerWorldCup', 'germany', 'weizen', 'reverse', 'all'],
"../../snd/R1S43.aif" : ['struck', 'schneiderWeisse', 'germany', 'weizen', 'reverse', 'all'],
"../../snd/R1S44.aif" : ['struck', 'jever', 'germany', 'pilsner', 'reverse', 'all'],
"../../snd/R1S45.aif" : ['struck', 'petrus', 'belgium', 'pokal', 'reverse', 'all'],
"../../snd/R1S46.aif" : ['struck', 'kostritzer', 'germany', 'pokal', 'reverse', 'all'],
"../../snd/R1S47.aif" : ['struck', 'spatenWillibecker', 'germany', 'becker', 'reverse', 'all'],
"../../snd/R1S48.aif" : ['struck', 'hoegaarden', 'belgium', 'pintGlass', 'reverse', 'all'],
"../../snd/R1S49.aif" : ['struck', 'samAdamsImperialPint', 'usa', 'pintGlass', 'reverse', 'all'],
"../../snd/R1S50.aif" : ['kill'],
"../../snd/R1S51.aif" : ['struck', 'imperialNonik', 'noCOA', 'pintGlass', 'reverse', 'all'], # do not use
"../../snd/R1S52.aif" : ['struck', 'glbcPint', 'usa', 'pintGlass', 'reverse', 'all'],
"../../snd/R1S53.aif" : ['struck', 'bbcNonik', 'usa', 'pintGlass', 'reverse', 'all'],
"../../snd/R1S54.aif" : ['struck', 'samSmithSmall', 'england', 'pintGlass', 'reverse', 'all'],
"../../snd/R1S55.aif" : ['struck', 'geordieSchooner', 'england', 'pintGlass', 'reverse', 'all'],
"../../snd/R1S56.aif" : ['struck', 'killiansRed', 'england', 'pintGlass', 'reverse', 'all'],
"../../snd/R1S57.aif" : ['struck', 'samSmithtulip', 'england', 'pintGlass', 'reverse', 'all'],
####sung####
"../../snd/S1S1.aif" : ['sung', 'fishbowlSnifter', 'noCOA', 'snifter', 'all'],
"../../snd/S1S2.aif" : ['sung', 'hommelbier', 'belgium', 'snifter', 'all'],
"../../snd/S1S3.aif" : ['sung', 'maudite', 'canada', 'snifter', 'all'],
"../../snd/S1S4.aif" : ['sung', 'bellsSnifter', 'usa', 'snifter', 'all'],
"../../snd/S1S5.aif" : ['sung', 'duvel', 'belgium', 'tulip', 'all'],
"../../snd/S1S6.aif" : ['sung', 'tripelKarmeliet', 'belgium', 'tulip', 'all'],
"../../snd/S1S7.aif" : ['sung', 'corsendonk', 'belgium', 'tulip', 'all'],
"../../snd/S1S8.aif" : ['sung', 'kwak', 'belgium', 'testTube', 'all'],
"../../snd/S1S9.aif" : ['sung', 'augustjin', 'belgium', 'chalice', 'all'],
"../../snd/S1S10.aif" : ['sung', 'leffe', 'belgium', 'chalice', 'all'],
"../../snd/S1S11.aif" : ['sung', 'grottenbier', 'belgium', 'chalice', 'all'],
"../../snd/S1S12.aif" : ['sung', 'troisPistoles', 'canada', 'chalice', 'all'],
"../../snd/S1S13.aif" : ['sung', 'stBernardus', 'belgium', 'canada', 'all'],
"../../snd/S1S14.aif" : ['sung', 'footedAleGlass', 'noCOA', 'pokal', 'all'],
"../../snd/S1S15.aif" : ['sung', 'schaflyKolsch', 'usa', 'kolsch', 'all'],
"../../snd/S1S16.aif" : ['kill'], #do not use
"../../snd/S1S17.aif" : ['sung', 'rootBeerFloat', 'noCOA', 'pokal', 'all'],
"../../snd/S1S18.aif" : ['sung', 'plainWeizen', 'noCOA', 'weizen', 'all'],
"../../snd/S1S19.aif" : ['sung', 'paulaner', 'germany', 'weizen', 'all'],
"../../snd/S1S20.aif" : ['sung', 'schneiderWeisse', 'germany', 'weizen', 'all'],
"../../snd/S1S21.aif" : ['sung', 'franziskaner', 'germany', 'weizen', 'all'],
"../../snd/S1S22.aif" : ['sung', 'pilsner', 'noCOA', 'pilsner', 'all'],
"../../snd/S1S23.aif" : ['sung', 'jever', 'germany', 'pilsner', 'all'],
"../../snd/S1S24.aif" : ['sung', 'petrus', 'belgium', 'pokal', 'all']
}